# frozen_string_literal: true

Institution.create!(
  [
    { name: 'Board of Regents of the University System of Georgia',
      institution_code: '01GALI_NETWORK',
      shortcode: 'usg',
      image: '',
      url: 'https://galileo-usg-uga-primo.hosted.exlibrisgroup.com/primo-explore/search?vid=UGA&search_scope=UGA&query=addsrcrid,exact,'},
    { name: 'Abraham Baldwin Agricultural College',
      institution_code: '01GALI_BALDWIN',
      shortcode: 'abac',
      image: '',
      url: 'https://galileo-usg-abac-primo.hosted.exlibrisgroup.com/primo-explore/search?vid=ABAC_V1&search_scope=ABAC&query=addsrcrid,exact,'},
    { name: 'Albany State University',
      shortcode: 'asu',
      institution_code: '01GALI_ALBANY',
      image: '',
      url: 'https://galileo-usg-asu-primo.hosted.exlibrisgroup.com/primo-explore/search?vid=ASU_V1&search_scope=ASU&query=addsrcrid,exact,'},
    { name: 'Atlanta Metropolitan College Library',
      shortcode: 'atlm',
      institution_code: '01GALI_ATLAMETRO',
      image: '',
      url: 'https://galileo-usg-atlm-primo.hosted.exlibrisgroup.com/primo-explore/search?vid=ATLM_V1&search_scope=ATLM&query=addsrcrid,exact,'},
    { name: 'Augusta University',
      shortcode: 'augusta',
      institution_code: '01GALI_AUG',
      image: '',
      url: 'https://galileo-usg-augusta-primo.hosted.exlibrisgroup.com/primo-explore/search?vid=AUGUSTA_V1&search_scope=AUGUSTA&query=addsrcrid,exact,'},
    { name: 'Clayton State University',
      shortcode: 'clayton',
      institution_code: '01GALI_CLAYTON',
      image: '',
      url: 'https://galileo-usg-clayton-primo.hosted.exlibrisgroup.com/primo-explore/search?vid=CLAYTON_V1&search_scope=CLAYTON&query=addsrcrid,exact,'},
    { name: 'College of Coastal Georgia',
      shortcode: 'ccga',
      institution_code: '01GALI_COASTLGA',
      image: '',
      url: 'https://galileo-usg-ccga-primo.hosted.exlibrisgroup.com/primo-explore/search?vid=CCGA_V1&search_scope=CCGA&query=addsrcrid,exact,'},
    { name: 'Columbus State University',
      shortcode: 'csu',
      institution_code: '01GALI_COLUMBUS',
      image: '',
      url: 'https://galileo-usg-csu-primo.hosted.exlibrisgroup.com/primo-explore/search?vid=CSU_V1&search_scope=CSU&query=addsrcrid,exact,'},
    { name: 'Dalton State College',
      shortcode: 'dalton',
      institution_code: '01GALI_DALTON',
      image: '',
      url: 'https://galileo-usg-dalton-primo.hosted.exlibrisgroup.com/primo-explore/search?vid=DALTON_V1&search_scope=DALTON&query=addsrcrid,exact,'},
    { name: 'East Georgia State College',
      shortcode: 'ega',
      institution_code: '01GALI_EAGEORG',
      image: '',
      url: 'https://galileo-usg-egsc-primo.hosted.exlibrisgroup.com/primo-explore/search?vid=EGSC_V1&search_scope=EGSC&query=addsrcrid,exact,'},
    { name: 'Fort Valley State University',
      shortcode: 'ftv',
      institution_code: '01GALI_FTVALLEY',
      image: '',
      url: 'https://galileo-usg-fvsu-primo.hosted.exlibrisgroup.com/primo-explore/search?vid=FVSU_V1&search_scope=FVSU&query=addsrcrid,exact,'},
    { name: 'Georgia College & State University',
      shortcode: 'gcsu',
      institution_code: '01GALI_GCSU',
      image: '',
      url: 'https://galileo-usg-gcsu-primo.hosted.exlibrisgroup.com/primo-explore/search?vid=GCSU_V1&search_scope=GCSU&query=addsrcrid,exact,'},
    { name: 'Georgia Gwinnett College',
      shortcode: 'ggc',
      institution_code: '01GALI_GWINNETT',
      image: '',
      url: 'https://galileo-usg-ggc-primo.hosted.exlibrisgroup.com/primo-explore/search?vid=GGC_V1&search_scope=GGC&query=addsrcrid,exact,'},
    { name: 'Georgia Institute of Technology',
      shortcode: 'tech',
      institution_code: '',
      image: '',
      url: 'https://www.library.gatech.edu/'},
    { name: 'Georgia Southern University',
      shortcode: 'gasou',
      institution_code: '01GALI_GASOUTH',
      image: '',
      url: 'https://galileo-usg-gasou-primo.hosted.exlibrisgroup.com/primo-explore/search?vid=GASOU&search_scope=GASOU&query=addsrcrid,exact,'},
    { name: 'Georgia Highlands College',
      shortcode: 'ghc',
      institution_code: '01GALI_FLOYD',
      image: '',
      url: 'https://galileo-usg-ghc-primo.hosted.exlibrisgroup.com/primo-explore/search?vid=GHC_V1&search_scope=GHC&query=addsrcrid,exact,'},
    { name: 'Georgia Southwestern State University',
      shortcode: 'gsw',
      institution_code: '01GALI_GSSU',
      image: '',
      url: 'https://galileo-usg-gswu-primo.hosted.exlibrisgroup.com/primo-explore/search?vid=GSWU_V1&search_scope=GSWU&query=addsrcrid,exact,'},
    { name: 'Georgia State University',
      shortcode: 'gsu',
      institution_code: '01GALI_GSU',
      image: '',
      url: 'https://galileo-usg-gsu-primo.hosted.exlibrisgroup.com/primo-explore/search?vid=GSU_V1&search_scope=GSU&query=addsrcrid,exact,'},
    { name: 'Gordon State College',
      shortcode: 'gordon',
      institution_code: '01GALI_GORDON',
      image: '',
      url: 'https://galileo-usg-gordon-primo.hosted.exlibrisgroup.com/primo-explore/search?vid=GORDON_V1&search_scope=GORDON&query=addsrcrid,exact,'},
    { name: 'Kennesaw State University',
      shortcode: 'ksu',
      institution_code: '01GALI_KENNESAW',
      image: '',
      url: 'https://galileo-usg-ksu-primo.hosted.exlibrisgroup.com/primo-explore/search?vid=KSU_V1&search_scope=KSU&query=addsrcrid,exact,'},
    { name: 'Middle Georgia State University',
      shortcode: 'mga',
      institution_code: '01GALI_MGA',
      image: '',
      url: 'https://galileo-usg-mga-primo.hosted.exlibrisgroup.com/primo-explore/search?vid=MGA_V1&search_scope=MGA&query=addsrcrid,exact,'},
    { name: 'Savannah State University',
      shortcode: 'savst',
      institution_code: '01GALI_SSU',
      image: '',
      url: 'https://galileo-usg-ssu-primo.hosted.exlibrisgroup.com/primo-explore/search?vid=SSU_V1&search_scope=SSU&query=addsrcrid,exact,'},
    { name: 'South Georgia State College',
      shortcode: 'sgsc',
      institution_code: '01GALI_SGC',
      image: '',
      url: 'https://galileo-usg-sgsc-primo.hosted.exlibrisgroup.com/primo-explore/search?vid=SGSC_V1&search_scope=SGSC&query=addsrcrid,exact,'},
    { name: 'University of Georgia',
      shortcode: 'uga',
      institution_code: '01GALI_UGA',
      image: '',
      url: 'https://galileo-usg-uga-primo.hosted.exlibrisgroup.com/primo-explore/search?vid=UGA&search_scope=UGA&query=addsrcrid,exact,'},
    { name: 'University of North Georgia',
      shortcode: 'ung',
      institution_code: '01GALI_UNG',
      image: '',
      url: 'https://galileo-usg-ung-primo.hosted.exlibrisgroup.com/primo-explore/search?vid=UNG_V1&search_scope=UNG&query=addsrcrid,exact,'},
    { name: 'University of West Georgia',
      shortcode: 'uwg',
      institution_code: '01GALI_UWG',
      image: '',
      url: 'https://galileo-usg-uwg-primo.hosted.exlibrisgroup.com/primo-explore/search?vid=UWG_V1&search_scope=UWG&query=addsrcrid,exact,'},
    { name: 'Valdosta State University',
      shortcode: 'vsu',
      institution_code: '01GALI_VALDOSTA',
      image: '',
      url: 'https://galileo-usg-vsu-primo.hosted.exlibrisgroup.com/primo-explore/search?vid=VSU&search_scope=VSU&query=addsrcrid,exact,'},
    { name: 'Georgia Department of Archives',
      shortcode: 'arch',
      institution_code: '01GALI_GADEPT',
      image: '',
      url: 'https://galileo-usg-archives-primo.hosted.exlibrisgroup.com/primo-explore/search?vid=ARCHIVES_V1&search_scope=ARCHIVES&query=addsrcrid,exact,'},
    { name: 'Georgia Piedmont Technical College',
      shortcode: 'gptc',
      institution_code: '01GALI_GPTC',
      image: '',
      url: 'https://galileo-usg-gptc-primo.hosted.exlibrisgroup.com/primo-explore/search?vid=GPTC_V1&search_scope=GPTC&query=addsrcrid,exact,'}
  ]
)