# frozen_string_literal: true

Institution.create!(
  [
    { name: 'Board of Regents of the University System of Georgia',
      institution_code: '01GALI_NETWORK',
      shortcode: 'usg',
      image: '' },
    { name: 'Abraham Baldwin Agricultural College',
      institution_code: '01GALI_BALDWIN',
      shortcode: 'abac',
      image: '' },
    { name: 'Albany State University',
      shortcode: 'asu',
      institution_code: '01GALI_ALBANY',
      image: '' },
    { name: 'Atlanta Metropolitan College Library',
      shortcode: 'atlm',
      institution_code: '01GALI_ATLAMETRO',
      image: '' },
    { name: 'Augusta University',
      shortcode: 'augusta',
      institution_code: '01GALI_AUG',
      image: '' },
    { name: 'Clayton State University',
      shortcode: 'clayton',
      institution_code: '01GALI_CLAYTON',
      image: '' },
    { name: 'College of Coastal Georgia',
      shortcode: 'ccga',
      institution_code: '01GALI_COASTLGA',
      image: '' },
    { name: 'Columbus State University',
      shortcode: 'csu',
      institution_code: '01GALI_COLUMBUS',
      image: '' },
    { name: 'Dalton State College',
      shortcode: 'dalton',
      institution_code: '01GALI_DALTON',
      image: '' },
    { name: 'East Georgia State College',
      shortcode: 'ega',
      institution_code: '01GALI_EAGEORG',
      image: '' },
    { name: 'Fort Valley State University',
      shortcode: 'ftv',
      institution_code: '01GALI_FTVALLEY',
      image: '' },
    { name: 'Georgia College & State University',
      shortcode: 'gcsu',
      institution_code: '01GALI_GCSU',
      image: '' },
    { name: 'Georgia Gwinnett College',
      shortcode: 'ggc',
      institution_code: '01GALI_GWINNETT',
      image: '' },
    { name: 'Georgia Institute of Technology',
      shortcode: 'tech',
      institution_code: '',
      image: '' },
    { name: 'Georgia Southern University',
      shortcode: 'gasou',
      institution_code: '01GALI_GASOUTH',
      image: '' },
    { name: 'Georgia Highlands College',
      shortcode: 'ghc',
      institution_code: '01GALI_FLOYD',
      image: '' },
    { name: 'Georgia Southwestern State University',
      shortcode: 'gsw',
      institution_code: '01GALI_GSSU',
      image: '' },
    { name: 'Georgia State University',
      shortcode: 'gsu',
      institution_code: '01GALI_GSU',
      image: '' },
    { name: 'Gordon State College',
      shortcode: 'gordon',
      institution_code: '01GALI_GORDON',
      image: '' },
    { name: 'Kennesaw State University',
      shortcode: 'ksu',
      institution_code: '01GALI_KENNESAW',
      image: '' },
    { name: 'Middle Georgia State University',
      shortcode: 'mga',
      institution_code: '01GALI_MGA',
      image: '' },
    { name: 'Savannah State University',
      shortcode: 'savst',
      institution_code: '01GALI_SSU',
      image: '' },
    { name: 'South Georgia State College',
      shortcode: 'sgsc',
      institution_code: '01GALI_SGC',
      image: '' },
    { name: 'University of Georgia',
      shortcode: 'uga',
      institution_code: '01GALI_UGA',
      image: '' },
    { name: 'University of North Georgia',
      shortcode: 'ung',
      institution_code: '01GALI_UNG',
      image: '' },
    { name: 'University of West Georgia',
      shortcode: 'uwg',
      institution_code: '01GALI_UWG',
      image: '' },
    { name: 'Valdosta State University',
      shortcode: 'vsu',
      institution_code: '01GALI_VALDOSTA',
      image: '' },
    { name: 'Georgia Department of Archives',
      shortcode: 'arch',
      institution_code: '01GALI_GADEPT',
      image: '' },
    { name: 'Georgia Piedmont Technical College',
      shortcode: 'gptc',
      institution_code: '01GALI_GPTC',
      image: '' }
  ]
)