# frozen_string_literal: true

Institution.create!(
  [
    { name: 'Board of Regents of the University System of Georgia',
      institution_code: '01GALI_NETWORK',
      image: '' },
    { name: 'Abraham Baldwin Agricultural College',
      institution_code: '01GALI_BALDWIN',
      image: '' },
    { name: 'Albany State University',
      institution_code: '01GALI_ALBANY',
      image: '' },
    { name: 'Armstrong State University',
      institution_code: '01GALI_ARMSTRONG',
      image: '' },
    { name: 'Atlanta Metropolitan College Library',
      institution_code: '01GALI_ATLAMETRO',
      image: '' },
    { name: 'Augusta University',
      institution_code: '01GALI_AUG',
      image: '' },
    { name: 'Bainbridge State College',
      institution_code: '01GALI_BAINBRIDGE',
      image: '' },
    { name: 'Clayton State University',
      institution_code: '01GALI_CLAYTON',
      image: '' },
    { name: 'College of Coastal Georgia',
      institution_code: '01GALI_COASTLGA',
      image: '' },
    { name: 'Columbus State University',
      institution_code: '01GALI_COLUMBUS',
      image: '' },
    { name: 'Dalton State College',
      institution_code: '01GALI_DALTON',
      image: '' },
    { name: 'Darton State College',
      institution_code: '',
      image: '' },
    { name: 'East Georgia State College',
      institution_code: '01GALI_EAGEORG',
      image: '' },
    { name: 'Fort Valley State University',
      institution_code: '01GALI_FTVALLEY',
      image: '' },
    { name: 'Georgia College & State University',
      institution_code: '01GALI_GCSU',
      image: '' },
    { name: 'Georgia Gwinnett College',
      institution_code: '01GALI_GWINNETT',
      image: '' },
    { name: 'Georgia Southern University',
      institution_code: '01GALI_GASOUTH',
      image: '' },
    { name: 'Georgia Highlands College',
      institution_code: '01GALI_FLOYD',
      image: '' },
    { name: 'Georgia Southwestern State University',
      institution_code: '01GALI_GSSU',
      image: '' },
    { name: 'Georgia State University',
      institution_code: '01GALI_GSU',
      image: '' },
    { name: 'Gordon State College',
      institution_code: '01GALI_GORDON',
      image: '' },
    { name: 'Kennesaw State University',
      institution_code: '01GALI_KENNESAW',
      image: '' },
    { name: 'Middle Georgia State University',
      institution_code: '01GALI_MGA',
      image: '' },
    { name: 'Savannah State University',
      institution_code: '01GALI_SSU',
      image: '' },
    { name: 'South Georgia State College',
      institution_code: '01GALI_SGC',
      image: '' },
    { name: 'University of Georgia',
      institution_code: '01GALI_UGA',
      image: '' },
    { name: 'University of North Georgia',
      institution_code: '01GALI_UNG',
      image: '' },
    { name: 'University of West Georgia',
      institution_code: '01GALI_UWG',
      image: '' },
    { name: 'Valdosta State University',
      institution_code: '01GALI_VALDOSTA',
      image: '' },
    { name: 'Georgia Department of Archives',
      institution_code: '01GALI_GADEPT',
      image: '' },
    { name: 'Georgia Piedmont Technical College',
      institution_code: '01GALI_GPTC',
      image: '' }
  ]
)